# Generated by Django 4.2.5 on 2025-10-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
