# Generated by Django 4.2.5 on 2025-10-29 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_tweetimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetimage',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.tweet', unique=True),
        ),
    ]
