# Generated by Django 4.2.5 on 2025-11-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_retweet_like_comment'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user', 'tweet'), name='like_unique'),
        ),
        migrations.AddConstraint(
            model_name='retweet',
            constraint=models.UniqueConstraint(fields=('user', 'tweet'), name='retweet_unique'),
        ),
    ]
