# Generated by Django 4.2.5 on 2025-11-18 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetweetNotify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.retweet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LikeNotify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.like')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentNotify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='retweetnotify',
            constraint=models.UniqueConstraint(fields=('user', 'retweet'), name='retweet_notify_unique'),
        ),
        migrations.AddConstraint(
            model_name='likenotify',
            constraint=models.UniqueConstraint(fields=('user', 'like'), name='like_notify_unique'),
        ),
        migrations.AddConstraint(
            model_name='commentnotify',
            constraint=models.UniqueConstraint(fields=('user', 'comment'), name='comment_notify_unique'),
        ),
    ]
