# Generated by Django 4.2.5 on 2025-10-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_header_image_customuser_icon_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
