# Generated by Django 4.2.5 on 2025-10-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_header_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='icon_image',
            field=models.ImageField(default='images/default-profile-icon.jpg', upload_to='images/'),
        ),
    ]
