# Generated by Django 4.2.5 on 2025-10-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_icon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='header/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='icon_image',
            field=models.ImageField(default='defaults/default-profile-icon.jpg', upload_to='icon/'),
        ),
    ]
