# Generated by Django 4.2.5 on 2025-10-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_header_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='icon/'),
        ),
    ]
