# Generated by Django 4.2.5 on 2025-10-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_icon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_id',
            field=models.CharField(blank=True, default='gvhg2hJsGyE'),
        ),
    ]
