# Generated by Django 4.2.5 on 2025-10-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_id',
            field=models.CharField(blank=True, default='eUqqTAb-nhU'),
        ),
    ]
