# Generated by Django 4.2.5 on 2025-10-31 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_customuser_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_id',
            field=models.SlugField(blank=True, default='vJ6Lngzb7eU', unique=True),
        ),
    ]
